from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(747, 600)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Add_button = QtWidgets.QPushButton(self.centralwidget)
        self.Add_button.setGeometry(QtCore.QRect(20, 330, 131, 101))
        self.Add_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Pictures/add_button_.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Add_button.setIcon(icon)
        self.Add_button.setIconSize(QtCore.QSize(100, 100))
        self.Add_button.setObjectName("Add_button")
        self.Delete_button = QtWidgets.QPushButton(self.centralwidget)
        self.Delete_button.setGeometry(QtCore.QRect(210, 330, 131, 101))
        self.Delete_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Pictures/delete_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Delete_button.setIcon(icon1)
        self.Delete_button.setIconSize(QtCore.QSize(100, 100))
        self.Delete_button.setObjectName("Delete_button")
        self.view_button = QtWidgets.QPushButton(self.centralwidget)
        self.view_button.setGeometry(QtCore.QRect(400, 330, 131, 101))
        self.view_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Pictures/view_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.view_button.setIcon(icon2)
        self.view_button.setIconSize(QtCore.QSize(90, 90))
        self.view_button.setObjectName("view_button")
        self.search_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_button.setGeometry(QtCore.QRect(590, 330, 131, 101))
        self.search_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Pictures/search_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_button.setIcon(icon3)
        self.search_button.setIconSize(QtCore.QSize(90, 90))
        self.search_button.setObjectName("search_button")
        self.Exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.Exit_button.setGeometry(QtCore.QRect(210, 450, 321, 101))
        self.Exit_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Pictures/exit_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Exit_button.setIcon(icon4)
        self.Exit_button.setIconSize(QtCore.QSize(100, 80))
        self.Exit_button.setObjectName("Exit_button")
        self.Sorton = QtWidgets.QLabel(self.centralwidget)
        self.Sorton.setGeometry(QtCore.QRect(130, 20, 511, 131))
        self.Sorton.setText("")
        self.Sorton.setPixmap(QtGui.QPixmap("Pictures/sorton.png"))
        self.Sorton.setObjectName("Sorton")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(390, 190, 271, 101))
        self.lcdNumber.setObjectName("lcdNumber")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 150, 201, 161))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Pictures/library2.png"))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 747, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

# main loop
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Video = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(Video)
    Video.show()

    # timer for resyncing app
    #timer = QtCore.QTimer()
    #timer.timeout.connect(ui.setTemp)
    #timer.start(10000)
    
    sys.exit(app.exec_())


